### ISSUE TITLE
Multithreading an multicore

### ISSUE THREAD

**Issue by Trankilloman** [krebeljk/openInjMoldSim#2]
Hi,
thanks for your tool but, its possible to launch slover with multithreading / multicore ?
Thanks

**Comment by Trankilloman** [comment]
*MultiProcessing

**Comment by krebeljk** [comment]
Yes, check the `AllRunPar` (parallel) script. The file machines will be read. It only says `localhost` in there which should work on a single machine. On a cluster, you list the node IPs.
